version: "3.3"
services:
    db:
        container_name: mydb
        image: mysql:8.0
        ports:
            - "32001:3306"
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
            # - dbdata:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        container_name: myapp
        build: ./
        volumes:
        - ./:/usr/control_center
        links:
            - "db"
        build: ./
        ports:
            - "5001:5000"
        environment:
            SQL_USER: root
            SQL_PASS: root
# volumes:
  # dbdata: